name: "Build Meower Desktop"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'
      - name: Install Dependencies
        run: npm install
      - name: Build the app
        run: npm run make
      - name: Publish artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: out/make/**/*
